DSM_CRITERIA = {
    'MDD': 'Major Depressive Disorder: Depressed mood most of the day, nearly every day. Markedly diminished interest or pleasure in all activities. Significant weight/appetite change. Insomnia or hypersomnia. Psychomotor changes. Fatigue. Worthlessness/guilt. Diminished concentration. Suicidal thoughts. Specifiers include anxious distress, mixed features, melancholic, atypical, psychotic, peripartum, seasonal. First-line: CBT + SSRI/SNRI.',
    'GAD': 'Generalized Anxiety Disorder: Excessive anxiety/worry >6 months, difficult to control. Restlessness, fatigue, concentration problems, irritability, muscle tension, sleep disturbance. First-line: CBT (worry exposure, mindfulness), SSRIs/SNRIs.',
    'PTSD': 'Posttraumatic Stress Disorder: Exposure to trauma + intrusion symptoms (memories, nightmares, flashbacks), avoidance, negative alterations in cognition/mood, hyperarousal (hypervigilance, startle, insomnia). Specifiers: dissociative symptoms, delayed expression. First-line: Trauma-focused CBT (PE, CPT, EMDR).',
    'BIPOLAR_II': 'Bipolar II Disorder: Hypomanic episodes (4+ days elevated/irritable mood + increased energy, 3+ symptoms: grandiosity, decreased sleep need, pressured speech, flight of ideas, distractibility, goal-directed activity, risky behavior) + Major Depressive episodes. No full mania. First-line: Quetiapine, lurasidone, lamotrigine, lithium; IPSRT + CBT.',
    'PANIC': 'Panic Disorder: Recurrent unexpected panic attacks (abrupt intense fear/discomfort peaking in minutes with 4+ somatic/cognitive symptoms) + 1 month of worry about attacks or maladaptive behavior change. Often with agoraphobia. First-line: CBT (interoceptive exposure) + SSRI.',
    'SOCIAL_ANXIETY': 'Social Anxiety Disorder: Marked fear of social/performance situations with scrutiny, fear of negative evaluation, avoidance or endurance with distress. Performance-only specifier. First-line: CBT exposure + SSRI.',
    'SOMATIC': 'Somatic Symptom Disorder: One+ distressing somatic symptoms + excessive thoughts/feelings/behaviors about them (disproportionate worry, high health anxiety, excessive time/energy). Persistent >6 months. First-line: CBT focused on illness beliefs and reduced reassurance-seeking.',
    'ADHD': 'Attention-Deficit/Hyperactivity Disorder: Persistent inattention and/or hyperactivity-impulsivity (6+ symptoms each domain) across settings, onset before 12, functional impairment. Presentations: Combined, Inattentive, Hyperactive/Impulsive. First-line: Stimulants + CBT/organizational skills training.',
    'OCD': 'Obsessive-Compulsive Disorder: Obsessions (intrusive thoughts/urges/images causing distress) and/or compulsions (repetitive behaviors/mental acts to reduce distress, not realistically connected). Time-consuming or impairing. First-line: Exposure and Response Prevention (ERP) CBT + SSRI at high dose.'
}
